version: '3.6'

services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: 'azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001'
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

networks:
  docker-network:
    driver: bridge

