# @name get-functions
GET http://localhost:49371/admin/functions

###

# @name post-timer-trigger
POST http://localhost:49371/admin/functions/TimerTriggerExample
Content-Type: application/json

{
  "input": "test"
}

###

# @name get-http-trigger
GET http://localhost:49371/api/HttpTriggerGetExample?name=Igor

###

# @name post-http-trigger
POST http://localhost:49371/api/HttpTriggerPostExample
Content-Type: application/json

{
  "name": "Joao",
  "gender": "MALE"
}
